name: Files View

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: show filetrees
      run: |
        ls -R
